version: '2'
services:
  pihole:
    hostname: pihole-rpi
    restart: unless-stopped
    container_name: pihole
    image: pihole/pihole 
    volumes:
      - /home/pi/pihole/configs/pihole:/etc/pihole/
      - /home/pi/pihole/configs/dnsmasq.d:/etc/dnsmasq.d/
    environment:
      - ServerIP=192.168.1.3          #Change for your own's raspberry IP
      - WEBPASSWORD=myencryptedpass   #choose your pihole UI password
      - DNS1=208.67.222.222           #DNS server1
      - DNS2=208.67.220.220           #DNS server2
      - IPv6=False
    cap_add:
      - NET_ADMIN
    ports:
      - "53:53/tcp"                   #required ports
      - "53:53/udp"
      - "80:80"
      - "443:443/tcp"
    dns:
      - 127.0.0.1                     #avoids issues when booting pihole for the first time
      - 8.8.8.8
